name: Publish docker image with jib
description: Builds and publishes docker image with jib

inputs:
  project:
    required: true
    description: Top level project to use as parent group for image
  gradle_project:
    required: true
    description: Gradle project
  service:
    required: true
    description: Gradle service
  tag:
    required: true
    description: Tag for the docker image
  google_sa_key:
    required: true
    description: GCS Service Account Json Key
  registry:
    required: true
    description: GCS Artifact registry
  java_version:
    required: false
    description: Java version
    default: '17'

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.google_sa_key }}
    - uses: google-github-actions/setup-gcloud@master
    - shell: bash
      run: gcloud auth configure-docker ${{ inputs.registry }}
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
        distribution: liberica
        cache: gradle
    - shell: bash
      run: |
        ./gradlew ${{ inputs.gradle_project }}:jib --image ${{ inputs.registry }}/${{ inputs.project }}/${{ inputs.service }}:${{ inputs.tag }} -Djib.console=plain --no-daemon
