name: Kind Cluster with Istio

inputs:
  team:
    required: true
    type: string
  component:
    required: true
    type: string
  tag:
    required: true
    type: string
  googlecreds:
    required: true
    type: string
  registry:
    required: true
    type: string

runs:
  using: "composite"
  container: google/cloud-sdk
  steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ inputs.googlecreds }}
        export_default_credentials: true
    - name: Configure gcloud for docker artifact registry
      shell: bash
      run: gcloud auth configure-docker ${{ inputs.registry }}
    - name: Publish with jib
      run: ./gradlew jib --image ${{ inputs.registry }}/${{ inputs.team }}/${{ inputs.component }}:${{ inputs.tag }} --stacktrace