name: Kind Cluster with Istio

inputs:
  namespace:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.2.0
    - name: Install Istio
      uses: bilelkhalsi/istio-action@v0.1.0
      with:
        version: 1.11.3
        profile: default
    - name: Create kubernetes namespace with istio injection enabled
      shell: bash
      run: |
        kubectl create namespace ${{ inputs.namespace }}
        kubectl label namespace ${{ inputs.namespace }} istio-injection=enabled --overwrite