name: Kind Cluster with Istio

inputs:
  namespace:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Install latest version of Kind
      shell: bash
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      shell: bash
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster