name: Build and release
description: Builds, releases and publishes libraries

inputs:
  google_sa_key:
    required: true
    description: GCS Service Account Json Key
  release_username:
    required: true
    description: username for pushing release tags
  release_password:
    required: true
    description: password for pushing release tags
  java_version:
    required: false
    description: Java version
    default: '17'

runs:
  using: "composite"
  steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: GCP authentication
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ inputs.google_sa_key }}
    - name: Setup GCP
      uses: google-github-actions/setup-gcloud@v0
    - name: Setup java
      uses: actions/setup-java@v2
      with:
        java-version: ${{ inputs.java_version }}
        distribution: liberica
        cache: gradle
    - name: Build and test
      shell: bash
      run: ./gradlew clean build --no-daemon
    - name: Generate test report
      uses: mikepenz/action-junit-report@v2
      if: always()
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
    - name: Release
      if: ${{ github.ref == 'refs/heads/main' }}
      shell: bash
      run: ./gradlew release --no-daemon
        -Prelease.customUsername=${{ inputs.release_username }}
        -Prelease.customPassword=${{ inputs.release_password }}
    - name: Publish
      shell: bash
      run: ./gradlew publish --no-daemon --no-parallel
