name: Publish artifact with maven to google artifact registry

inputs:
  googlecreds:
    required: true
    type: string
  registry:
    required: true
    type: string

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ inputs.googlecreds }}
        export_default_credentials: true
    - name: Configure gcloud
      shell: bash
      run: | # Regex to get the registry name/id and location from a gcp artifact registry uri
        function regex { gawk 'match($0,/'$1'/, ary) {print ary['${2:-'0'}']}'; }
        PATTERN='.+\/\/(\w.+)-maven.+\/(\w+)'
        LOCATION=$(echo ${{ inputs.registry }} | regex $PATTERN 1)
        REGISTRY_NAME=$(echo ${{ inputs.registry }} | regex $PATTERN 2)
        echo $LOCATION
        echo $REGISTRY_NAME
        gcloud config set artifacts/repository $REGISTRY_NAME
        gcloud config set artifacts/location $LOCATION
    - name: Publish with maven-publish
      shell: bash
      run: ./gradlew publish --stacktrace