name: Kind Cluster with Istio

on:
  workflow_call:
    inputs:
      namespace:
        required: true
        type: string
#    secrets:
#      token:
#        required: true

jobs:
  setup-cluster:
    name: Create a Kind cluster with Istio
    runs-on: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: 1.13
    - name: Install latest version of Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster --config kind/kind-config.yaml
    - name: Run some sanity checks
      # kubectl is already installed on the Github Ubuntu worker
      run: |
        kubectl get nodes -o wide
        kubectl get pods --all-namespaces -o wide
        kubectl get services --all-namespaces -o wide